//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public int Id { get; set; }
        public int ReservaId { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Monto { get; set; }
        public string Metodo { get; set; }
    
        public virtual Reservas Reservas { get; set; }
    }
}
